### ISSUE TITLE
NullPointerException for invalid url

### ISSUE THREAD

**Issue by fadjer** [cmarchand/gaulois-pipe#44]
Hi,

While running last version of Gaulois Pipe within my project, I'm getting this NullPointerException : 

```
java.lang.NullPointerException: null
	at com.saxonica.ee.schema.sdoc.SchemaReader.read(SchemaReader.java:140) ~[saxonee-9.8.0.14.jar!/:na]
	at com.saxonica.config.EnterpriseConfiguration.addSchemaSource(EnterpriseConfiguration.java:630) ~[saxonee-9.8.0.14.jar!/:na]
	at net.sf.saxon.Configuration.addSchemaSource(Configuration.java:3025) ~[saxonee-9.8.0.14.jar!/:na]
	at fr.efl.chaine.xslt.GauloisPipe.launch(GauloisPipe.java:251) ~[gaulois-pipe-1.03.05.jar!/:na]
```
Just before this error, I get this log witch shows a invalid url path : 

`Loading schema cp:/gc\schemas\query.xsd`

Thanks in advance

**Comment by cmarchand** [comment]
This is a normal behavior, as your schema URI is invalid. See [gaulois-compiler issue #4](https://github.com/cmarchand/gaulois-compiler-maven-plugin/issues/4).

We may add a control on config file to check that schema URI is valid. I re-open this issue, changing the title, for further improvements
