### ISSUE TITLE
Config checks enhancements

### ISSUE THREAD

**Issue by jimetevenard** [cmarchand/gaulois-pipe#49]
## No `output` at the end of a `pipe`.
The error message is sufficiently explicit.
But this could be constrained in the schema.

**Moreover**, Exceptions that are thrown at runtime are caught and added into the pipe's errors stack (which is a `List<String>` ).  

This introduces a difference of behavior between problems that are pretty much identical (Mistake in config)

## `choose` /`tee` as first child of main `pipe`
This problem is already known, cf. [Issue 23]
(https://github.com/cmarchand/gaulois-pipe/issues/23)

But this is allowed the schema.
It fails only at runtime, with an exception message which does not make sense without rifling through the code.
```
java.lang.IllegalArgumentException: assignee must not be null
	at fr.efl.chaine.xslt.GauloisPipe.assignStepToDestination(GauloisPipe.java:772)
	at fr.efl.chaine.xslt.GauloisPipe.buildTransformer(GauloisPipe.java:764)
	at fr.efl.chaine.xslt.GauloisPipe.buildTransformer(GauloisPipe.java:578)
	at fr.efl.chaine.xslt.GauloisPipe.executesPipeOnMultiThread(GauloisPipe.java:364)
	at fr.efl.chaine.xslt.GauloisPipe.launch(GauloisPipe.java:293)
```

**Comment by cmarchand** [comment]
Closed by Pull Request, merged on 2019/09/05
